### ISSUE TITLE
pre-processor definitions are not processed properly

### ISSUE THREAD

**Issue by extrakteon** [gerald-lindsly/mongo-matlab-driver#2]
I get the following problem when trying to load the library in Linux (MATLAB 2010b 32- and 64-bit).

The library compiles just fine (then the pre-processor stuff works) but MATLAB doesn't like it.

[notfound, warnings] = loadlibrary('MongoMatlabDriver.so', 'MongoMatlabDriver.h');
??? Error using ==> loadlibrary at 365
Failed to preprocess the input file.
 Output from preprocessor is:In file included from
 /home/e7koffe/git/mongo-matlab-driver/MongoMatlabDriver.h:38:0:
/home/e7koffe/git/mongo-matlab-driver/platform.h:50:2: error: #error must have a 64bit int type

I could try to merge platform.h into the MongoMatlabDriver.h and set all the options manually.

**Comment by gerald-lindsly** [comment]
Someone else has reported this problem.  Perhaps **GNUC** is not defined
when Matlab launches the compiler?

On Tue, Feb 14, 2012 at 3:30 PM, Kristoffer Andersson <
reply@reply.github.com

**Comment by extrakteon** [comment]
The following fixes work:

1) define MONGO_HAVE_STDINT in "platform.h"
2) fix some typos ("mxint64" should be "mxInt64" in "MongoMatlabDriver.h"
3) include "/usr/local/MATLAB/R2010b/extern/include/mclmcrrt.h" in "MongoMatlabDriver.h"

now the library loads and the MongoTest.m script works!

**Comment by gerald-lindsly** [comment]
1 & 3 sound fine.  but 2...   mxint64 is my own defined name and is not
part of the Matlab 'standard'.  Case should not matter.

Thanks for figuring that out for me.

On Tue, Feb 14, 2012 at 3:56 PM, Kristoffer Andersson <
reply@reply.github.com

**Comment by gerald-lindsly** [comment]
Since the code works as-is for most (and myself), I am going to close this issue and refer folks to your fix if it comes up again.  Due to some quirk of Matlab, the definition of MONGO_HAVE_STDINT is being ignored in MongoMatlabDriver.h, but rightfully the definition should be _there_.  The include you gave for mclmcrrt.h is Matlab version dependent and this also seems to be another quirk of Matlab versioning as to whether it is needed.
